version: '3'
services:
  web:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE_NAME}:${WEB_IMAGE_TAG}
    environment:
      - HOST=${WEB_DB_HOST}
      - PORT=${WEB_DB_PORT}
      - USER=${WEB_DB_USER}
      - PASSWORD=${WEB_DB_PASSWORD}
      - DB=${POSTGRES_DB}
    build: ./
    ports:
      - "${WEB_PORT}:8069"
    volumes:
      - /odoo-volumes/var-lib-odoo:/var/lib/odoo
      - /odoo-volumes/etc-odoo:/etc/odoo
      - /odoo-volumes/mnt-extra-addons:/mnt/extra-addons
      - /odoo-volumes/mnt-extra-addons-customize:/mnt/extra-addons-customize
    #entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /nginx-volumes/etc-nginx-conf:/etc/nginx/conf.d
      - /nginx-volumes/etc-nginx-ssl:/etc/nginx/ssl
      - /nginx-volumes/var-www-html:/var/www/html
volumes:
  var-lib-odoo:
